package com.crepen.crepenboard.api.module.admin.config.model;

public enum SiteConfigKey {



    // ACCOUNT_ID
    ACCOUNT_ID_MINIMUM_LENGTH,
    ACCOUNT_ID_MAXIMUM_LENGTH,
    ACCOUNT_ID_ALLOW_SYMBOL,

    // ACCOUNT_PASSWORD
    ACCOUNT_PASSWORD_MINIMUM_LENGTH,
    ACCOUNT_PASSWORD_MAXIMUM_LENGTH,
    ACCOUNT_PASSWORD_REQUIRED_NUMBER,
    ACCOUNT_PASSWORD_REQUIRED_SYMBOL,
    ACCOUNT_PASSWORD_REQUIRED_UPPER_ENG,
    ACCOUNT_PASSWORD_ALLOW_SYMBOL,


    // ACCOUNT_COMMON
    ACCOUNT_TERMINATE_GRACE_PERIOD_SECOND,
    ACCOUNT_TERMINATE_ENABLE_GRACE_PERIOD,


    SITE_INIT,
}
