server:
  servlet:
    context-path: /api


spring:
  datasource:
    url:
    username:
    password:
    driver-class-name: org.mariadb.jdbc.Driver
  application:
    name: crepen-board-api
  jackson:
    # Controller JSON Return 시 null 항목 제거
    default-property-inclusion: non_null
  servlet:
    multipart:
      enabled: true
      max-file-size: 2GB
      max-request-size: 2GB
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  output:
    ansi:
      enabled: ALWAYS


jwt:
  secret: 62a81afe948890cdecec70aff9872641